package com.supermarket.auth.infrastructure.config;

import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Contact;
import io.swagger.v3.oas.models.info.Info;

/**
 * OpenAPI/Swagger configuration for the Auth Service application.
 *
 * <p>
 * This configuration customizes the OpenAPI specification that is automatically
 * generated by SpringDoc. It provides API metadata including title, version,
 * description, and contact information. The generated OpenAPI specification is
 * available at:
 *
 * <ul>
 * <li>/v3/api-docs - JSON format
 * <li>/v3/api-docs.yaml - YAML format
 * <li>/swagger-ui.html - Interactive Swagger UI
 * </ul>
 *
 * @author Ignacio Agüero Salcines
 * @since 1.0
 */
@Configuration
public class OpenApiConfig {

    /**
     * Customizes the OpenAPI specification metadata.
     *
     * <p>
     * Provides API title, version, description, and contact details that are
     * displayed in the Swagger UI and OpenAPI documentation.
     *
     * @return configured OpenAPI instance with custom metadata
     */
    @Bean
    public OpenAPI customOpenAPI() {
        return new OpenAPI()
                .info(new Info().title("Auth Service API").version("v1").description("API for Authentication service")
                        .contact(new Contact().name("Supermarket Team").email("test@example.com")));
    }
}
